### ISSUE TITLE
ZZZMap was not build, Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by WatchAndyTW** [Razmoth/ZZZStudio#1]
![image](https://user-images.githubusercontent.com/51250139/183229776-a41180d6-934d-4291-a833-221a8061639f.png)
I was trying to build the ZZZMap, but then this warning message came out.

**Comment by Razmoth** [comment]
greetings.

which version of the game is this ?

**Comment by Razmoth** [comment]
might be fixed with ![f63886d](https://github.com/Razmoth/ZZZStudio/commit/f63886dcba4b3b5486a8eaa423a7b38182c94e60)

**Comment by WatchAndyTW** [comment]
Game version right here: ![image](https://user-images.githubusercontent.com/51250139/183243703-db44a3e5-7576-46dd-81ff-79a31eb44e4f.png)
But if I only build the map of the files in `Win_Data/StreamingAssets/Bundles` then this error message would pop out.
![image](https://user-images.githubusercontent.com/51250139/183243763-2cc64bbf-13f1-45b0-92d5-1909100bfeec.png)

**Comment by Razmoth** [comment]
updated release binaries.

**Comment by WatchAndyTW** [comment]
It works pretty well, thanks to your support and wish the best to your future projects.
