### ISSUE TITLE
Can't export animation clips

### ISSUE THREAD

**Issue by JasonHan233** [Razmoth/ZZZStudio#2]
I use "Animator + selected AnimationClips", it say"ACL.Acl threw an exception". Only export fbx model without AnimationClip can be done.

**Comment by Razmoth** [comment]
Greetings,

Last time `ACL` was working well for ZZZ (except humanoid animations ofc).

Which version, bundle and file are causing this issue ?

**Comment by JasonHan233** [comment]
> 

Latest version, 0.16.55, debug window no log output. zzz character Lycaon's Animator, export Animator with AnimationClip, show ACL.acl exception.

**Comment by JasonHan233** [comment]
Latest version, 0.16.55, debug window no log output. zzz character Lycaon's Animator, export Animator with AnimationClip, show ACL.acl exception.

**Comment by Razmoth** [comment]
Didn't try exporting with (`Animator` + selected `AnimationClip`s) before, will check it out.

In case you need to export all animations related to a character, you can untick `Options -> Export Options -> Ignore Controller Animations` as shown below.

![image](https://user-images.githubusercontent.com/32140579/183474156-4ccd35a0-c768-41e1-b319-264b35a2e460.png)

**Comment by JasonHan233** [comment]
I try that, and I try to ticked "Ignore Controller Animations" and use "Export Animator+Selected Animation Clip", and I select a AnimationClip, but it threw a exception again.

**Comment by JasonHan233** [comment]
Selected AnimationClip is belongs to the Animator

**Comment by JasonHan233** [comment]
Problem solved.
